### DISCUSSION TITLE
Is is possible to make plotman create more than 1 plot at a time?

### DISCUSSION THREAD

**Discussion by danielbodart** [ericaltendorf/plotman#235] [Q&A]
What I would like is that plotman create 2 jobs immediately and then maybe 30mins later another 2 jobs.  This is the config I currently have:

```
scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 2
        tmpdir_stagger_phase_limit: 4
        tmpdir_max_jobs: 6
        global_max_jobs: 999
        global_stagger_m: 30
        polling_time_s: 60
```

But with this config it still only creates a single job when it starts up. What am I doing wrong?
