### DISCUSSION TITLE
Plotting on different tmp drives

### DISCUSSION THREAD

**Discussion by andre-bender** [ericaltendorf/plotman#279] [Q&A]
Hey, I'm in love with plotman but I cant find an answer to my following question.

I have 2 tmp drives. One which is about 1 TB large (3 K32 would fit) and one that is 500 GB (1 K32 would fit). 
How can I configure plotman that 3 plots are plotted on the 1 TB drive and 1 plot on the 500 GB drive? I would like to do 4 K32 parallel.

**Comment by thomann061** [comment]
Assuming `00` is the 1TB drive and `01` is the 500GB drive.
```
tmp:
        - /mnt/tmp/00
        - /mnt/tmp/01

tmp_overrides:
        "/mnt/tmp/00":
                tmpdir_max_jobs: 3
        "/mnt/tmp/01":
                tmpdir_max_jobs: 1

scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1
        tmpdir_max_jobs: 4
        global_max_jobs: 4
        global_stagger_m: 60
        polling_time_s: 20
```
