### DISCUSSION TITLE
Use local drives for archiving?

### DISCUSSION THREAD

**Discussion by cyperbg** [ericaltendorf/plotman#413] [Q&A] [answered]
Plots are being created on tmp drives
When completed plots are moved dst drive, which is again a fast m.2 drive.
And finally they are moved from the dst drive to the slow permanent storage (HDDs) (external connected via USB)

Basically can you archive to locally connected drives?

The idea behind this is using the middle drive as sort of a temporary cache to help empty the fast drives, so new plots are started asap.

**Comment by chadmccune** [comment, marked as answer]
I think you could do this just by configuring archiving as normal, the only difference is the "remote" would actually be the local machine

**Reply by altendky** [reply]
That's exactly what you have to do for now.  It is silly.  That's why we are working on a more configurable archive setup.

https://github.com/ericaltendorf/plotman/wiki/Archiving

**Reply by pureevans** [reply]
could you please explain a little more detailed what you mean by archiving as normal? In the plotman.yaml you have this archiving part:
```yaml
archive:
        rsyncd_module: chia               # Module name specified in the Plot Storage's rsyncd.conf
        rsyncd_path: /mnt                 # Path where your storage drives are mounted (same as in rsyncd.conf)
        rsyncd_bwlimit: 100000            # Bandwidth limit in KB/s
        rsyncd_host: plot.storage.ip      # IP address or hostname of your Plot Storage
        rsyncd_user: username             # Username that can ssh into your Plot Storage
```
if my HDDs are local, how to I point plotman to them? Can i simply pass an Array like with the tmp drives? Which parameters are needed if it's local and not via rsyncd?
