### DISCUSSION TITLE
Help configuring plotman for 12 hdds and 24 threads. No ssds.

### DISCUSSION THREAD

**Discussion by danilocubrovic** [ericaltendorf/plotman#436] [Q&A]
I need help with plotman config
I'm trying to configure plotman but don't have knowledge deep enough to configure it properly for my system.

I m having 2 cpus Xeon E5645 (2cpu x 6 cores ~ 12 threads => 24 threads)

32GB RAM and 12 HDDs (3TB each)

Do not have ssd-s of any kind.

Can someone point me how to improve my config.

I have started it 30 mins ago but this goes currently with only one plot and low use of cpu so I must be doing something pretty pretty wrong :)

user_interface:

use_stty_size: True

directories:

log: /home/chia/chia/logs

tmp:

- /media/cubrovic/data2/chia2/temp2

- /media/cubrovic/data3/chia3/temp3

- /media/cubrovic/data4/chia4/temp4

- /media/cubrovic/data5/chia5/temp5

- /media/cubrovic/data6/chia6/temp6

- /media/cubrovic/data7/chia7/temp7

- /media/cubrovic/data8/chia8/temp8

- /media/cubrovic/data9/chia9/temp9

- /media/cubrovic/data10/chia10/temp10

- /media/cubrovic/data11/chia11/temp11

- /media/cubrovic/data12/chia12/temp12

# - tmpdir_max_jobs

# tmp_overrides:

# "/fs/chia1/temp1":

# tmpdir_max_jobs: 11

# Optional: tmp2 directory. If specified, will be passed to

# chia plots create as -2. Only one tmp2 directory is supported.

# tmp2: /mnt/tmp/a

dst:

- /media/cubrovic/data2/chia2/final2

- /media/cubrovic/data3/chia3/final3

- /media/cubrovic/data4/chia4/final4

- /media/cubrovic/data5/chia5/final5

- /media/cubrovic/data6/chia6/final6

- /media/cubrovic/data7/chia7/final7

- /media/cubrovic/data8/chia8/final8

- /media/cubrovic/data9/chia9/final9

- /media/cubrovic/data10/chia10/final10

- /media/cubrovic/data11/chia11/final11

- /media/cubrovic/data12/chia12/final12

# Plotting scheduling parameters

scheduling:

tmpdir_stagger_phase_major: 2

tmpdir_stagger_phase_minor: 1

# Optional: default is 1

tmpdir_stagger_phase_limit: 1

# Don't run more than this many jobs at a time on a single temp dir.

tmpdir_max_jobs: 3

# Don't run more than this many jobs at a time in total.

global_max_jobs: 11

# Don't run any jobs (across all temp dirs) more often than this, in minutes.

global_stagger_m: 30

# How often the daemon wakes to consider starting a new plot job, in seconds.

polling_time_s: 20

# Plotting parameters. These are pass-through parameters to chia plots create.

plotting:

k: 32

e: False # Use -e plotting option

n_threads: 20 # Threads per job

n_buckets: 128 # Number of buckets to split data into

job_buffer: 3389 # Per job memory

**Comment by thomann061** [comment]
It is probably beneficial to put some of the drives in raid0, and use others just for dst. You may get some performance gains from that. Overall you can run max jobs of ~8 maybe 9 at a time due to memory constraints. So 3-4 drives may never get used. This could be a start to figuring out what works for you.
```yaml
# Plotting scheduling parameters
scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1
        tmpdir_max_jobs: 1
        global_max_jobs: 8
        global_stagger_m: 60
        polling_time_s: 20

plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 2         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3389     # Per job memory
```
