### DISCUSSION TITLE
Plotman ignores major+minor+limt and uses global_stagger_m instead

### DISCUSSION THREAD

**Discussion by abra** [ericaltendorf/plotman#453] [Q&A]
Why does plotman only use global_stagger_m instead of major and minor stagger with limit?
I have the following options below and I think plotman should start a new plot only after the current task reaches stage 2:1, but plotman starts a new plot 15 minutes later according to global_stagger_m without waiting for stage 2:1 of the current stage.

plotman.yaml
```yaml
directories:
        log: /home/abra/chialogs
        tmp:
                - /mnt/kingstonnvme1/temp
                - /mnt/kingstonnvme2/temp
       dst:
                - /mnt/toshiba1/plots
                - /mnt/toshiba2/plots
                - /mnt/toshiba3/plots
                - /mnt/seagate1/plots
                - /mnt/seagate2/plots
                - /mnt/seagate8tb1/plots  
scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1
        tmpdir_max_jobs: 3
        global_max_jobs: 6
        global_stagger_m: 15
        polling_time_s: 20
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 12        # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 4440     # Per job memory
```
