### DISCUSSION TITLE
Having issues using poolkey

### DISCUSSION THREAD

**Discussion by Rizbe** [ericaltendorf/plotman#563] [Q&A] [answered]
Current version: `plotman 0.3.1`
Every time I run plotman plot
The jobs fail and see the following in the logs

 
farmer_public_key = G1Element.from_bytes(bytes.fromhex(args.farmer_public_key))
ValueError: non-hexadecimal number found in fromhex() arg at position 0

Below is a sample config 
```
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 2         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3389     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        farmer_pk: "KEY"
        pool_pk: "KEY"
        ```
