### DISCUSSION TITLE
Multiple tmp2 dirs

### DISCUSSION THREAD

**Discussion by JoshuaEstes** [ericaltendorf/plotman#570] [Ideas]
Similar to how tmp dirs are chosen, the tmp2 dirs could be chosen the same way. No need to over complicated it. Config example:
```yaml
tmp:
  - /mnt/tmp/00
  - /mnt/tmp/01
tmp2:
  - /mnt/tmp/00
  - /mnt/tmp/01
```

Another way to configure would be to configure both tmp and tmp2. So I could configure `/mnt/tmp/0` to use `/mnt/tmp2/0`. Config example:
```yaml
tmp:
  # No options
  "/mnt/tmp/00": ~
  "/mnt/tmp/01":
    tmp2: /mnt/tmp2/01
```

Personally I think that latter will give more opportunities for better configuration and you could move the `temp_overrides` here. The second option also allows to the possibility to have multiple tmp2 dirs that could be selected from.
