### DISCUSSION TITLE
Temp dirs issue?

### DISCUSSION THREAD

**Discussion by bmentink** [ericaltendorf/plotman#730] [General]
HI,

Love the software, make's plotting much easier. However ..

I am getting the error: "no eligible tempdirs (5617s/5100s)" when I plot.

I am only running two parallel plots with a 1TB SSD. I would have thought that since temporary storage takes 280GB per plot, there would be enough temp space ..

_Originally posted by @bmentink in https://github.com/ericaltendorf/plotman/discussions/725_

**Comment by altendky** [comment]
You will need to share your complete configuration file and the output from whatever mechanism you use to check the status of the plots.  Plots take peak 250GB and usually more like 200 on average, or perhaps a bit less.  I regularly run four on 1TB drives.  But, plotman doesn't do that count for you.  You have to configure it.

**Comment by byeuji** [comment]
Pasting what I wrote in the other thread:

If you're plotting in parallel or using the tmp2 feature, it might just be a temporary issue. What plotman probably means is "no eligible tempdirs *right now*"

You might also have the max jobs `tmpdir_max_jobs` setting too low -- with 1TB plotting drive, you should be able to set this to 4, since using plotman, not all jobs will be in Phase 2 at the same time. But personally, I'd recommend using the tmp2 feature of chia to avoid running out of space on tmp and gumming up your plots.

**Comment by bmentink** [comment]
@byeuji  Thanks. I can't run 4 plots as I am memory limited  (8GB). I would of thought that setting  _tmpdir_max_jobs_   to 2 would be fine when I am only ever running two plots at a time .. 

@altendky  As above , I am only ever using two plots at a time, so temp storage should not get above 500GB, so how is it I am getting the warning when I have 1TB, does not make sense ..

Relevant part of config is: 

```yaml
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before [tmpdir_stagger_phase_major : tmpdir_stagger_phase_minor]
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major : phase minor].
        # e.g, with default settings, a new plot will start only when your plot
        # reaches phase [2 : 1] on your temp drive. This setting takes precidence
        # over global_stagger_m
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 2

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 2

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 65

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20


plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 6         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3400     # Per job memory
```

EDIT: Is latest screenshot of warning ..
![Screen Shot 2021-06-05 at 11 38 54 AM](https://user-images.githubusercontent.com/10123911/120872382-bdae3400-c5f2-11eb-9821-5dc24fdbbb6f.png)
