### DISCUSSION TITLE
Help with respecting tmp_overrides

### DISCUSSION THREAD

**Discussion by snoby** [ericaltendorf/plotman#743] [Q&A]
I'm trying to put some prints in the code, but I seem to have a situation where tmp_overrides are not being respected.  

the config file:
```yaml
# Default/example plotman.yaml configuration file

# Options for display and rendering
user_interface:
        use_stty_size: True

# Where to plot and log.
directories:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        log: /mnt/logs 

        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - /mnt/rust/
                - /mnt/nvme/


        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        tmp_overrides:
                # In this example, /mnt/tmp/00 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                "/mnt/rust":
                        tmpdir_max_jobs: 4
                "/mnt/nvme":
                         tmpdir_max_jobs: 1

        dst:
                - /mnt/final



# Plotting scheduling parameters
scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 2

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 5

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 4

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 20

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20


plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 6         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 4096     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        #   farmer_pk: ...
        #   pool_pk: ...
```

so I take from that config that the nvme should never have more than 1 job running on it... however

``` bash
root@ca49fa00645b:/opt/chia-blockchain# plotman status
 plot id    k          tmp          dst   wall   phase    tmp     pid   stat    mem   user    sys     io
c734ec77   32   /mnt/nvme/   /mnt/final   0:04     1:1    23G   30262    SLP   1.1G   0:01    27s     0s
961fd272   32   /mnt/rust/   /mnt/final   1:06     1:3   129G   25194    STP   6.2G   0:48   0:02     5s
5e885113   32   /mnt/rust/   /mnt/final   2:13     2:0   169G   20744    RUN   2.7G   3:02   0:08   0:03
37621384   32   /mnt/nvme/   /mnt/final   6:16     1:7   179G    5077    STP   5.9G   5:43   0:09     6s
c3f778b3   32   /mnt/nvme/   /mnt/final   6:56     3:1   226G    1937    DSK   5.8G   4:37   0:14   0:32
```

I've tried putting some prints in the code here
https://github.com/ericaltendorf/plotman/blob/1876d4cbda73fb38584f95113a00f01af1e21704/src/plotman/manager.py#L67

However I don't see it hitting here even when I go into plotman interactive or when a new job starts.

What am I doing wrong?  Thanks,
