### DISCUSSION TITLE
new version(0.4)'s archiving path error

### DISCUSSION THREAD

**Discussion by StoneCX** [ericaltendorf/plotman#744] [Q&A]
error output
```
echo Launching transfer activity
+ echo Launching transfer activity
Launching transfer activity
relative_path=$(realpath --relative-to="${site_root}" "${destination}")
++ realpath --relative-to=/mnt/farmer /mnt/farmer/4t4
realpath: /mnt/farmer/4t4: No such file or directory
+ relative_path=
```
there are my config 
```
archiving:
  target: rsyncd
  index: 3
  env:
    site_root: /mnt/farmer
    user: x9011
    host: 192.168.1.4
    rsync_port: 12000
    site: farmer
    options: --bwlimit=80000 --preallocate --remove-source-files --skip-compress plot --whole-file

```

but the /mnt/farmer/4t4 is exist in 192.168.1.4 
the new version's config is confuse me . is anyone know that?
