### DISCUSSION TITLE
plotman does not run

### DISCUSSION THREAD

**Discussion by toboladao** [ericaltendorf/plotman#775] [Q&A]
I needed to format the server and now I'm not able to get plotman to run.
already tried as user and as root.
This message appears when I run the archive. 

```
> chia-blockchain$ plotman archive
> Traceback (most recent call last):
>   File "/home/ubuntu/chia-blockchain/venv/bin/plotman", line 8, in <module>
>     sys.exit(main())
>   File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 154, in main
>     cfg = configuration.get_validated_configs(config_text, config_path, preset_target_definitions_text)
>   File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 56, in get_validated_configs
>     raise Exception(message)
> Exception: Expected major version 1, found version (0,)
>     See https://github.com/ericaltendorf/plotman/wiki/Configuration#versions>

``````

my plotman.yaml is this:

```
`# Default/example plotman.yaml configuration file
# Options for display and rendering
user_interface:
        # Call out to the `stty` program to determine terminal size, instead of
        # relying on what is reported by the curses library.   In some cases,
        # the curses library fails to update on SIGWINCH signals.  If the
        # `plotman interactive` curses interface does not properly adjust when
        # you resize the terminal window, you can try setting this to True.
        use_stty_size: True
# Where to plot and log.
directories:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        log: /var/opt/chia/logs
        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - /mnt/ssd/tmp
                - /home/ubuntu/tmp
        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        tmp_overrides:
                # In this example, /mnt/tmp/00 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                "/mnt/ssd/tmp":
                        tmpdir_max_jobs: 3
                "/home/ubuntu/tmp":
                        tmpdir_max_jobs: 3
        # Optional: tmp2 directory.  If specified, will be passed to
        # chia plots create as -2.  Only one tmp2 directory is supported.
        # tmp2: /mnt/tmp/a
        # One or more directories; the scheduler will use all of them.
        # These again are presumed to be on independent physical devices,
        # so writes (plot jobs) and reads (archivals) can be scheduled
        # to minimize IO contention.
        dst:
                 - /home/ubuntu/final
                 - /mnt/ssd/final
        # Archival configuration.  Optional; if you do not wish to run the
        # archiving operation, comment this section out.
        #
        # Currently archival depends on an rsync daemon running on the remote
        # host.
        # The archival also uses ssh to connect to the remote host and check
        # for available directories. Set up ssh keys on the remote host to
        # allow public key login from rsyncd_user.
        # Complete example: https://github.com/ericaltendorf/plotman/wiki/Archiving
        archive:
                 rsyncd_module: chia # Define this in remote rsyncd.conf.
                 rsyncd_path: /mnt  # This is used via ssh. Should match path
        #                             # defined in the module referenced above.
                 rsyncd_bwlimit: 102400000  # Bandwidth limit in KB/s
                 rsyncd_host: xxx.xxx.xx.xx
                 rsyncd_user: ubuntu
                # Optional index.  If omitted or set to 0, plotman will archive
                # to the first archive dir with free space.  If specified,
                # plotman will skip forward up to 'index' drives (if they exist).
                # This can be useful to reduce io contention on a drive on the
                # archive host if you have multiple plotters (simultaneous io
                # can still happen at the time a drive fills up.)  E.g., if you
                # have four plotters, you could set this to 0, 1, 2, and 3, on
                # the 4 machines, or 0, 1, 0, 1.
                #   index: 0
# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before [tmpdir_stagger_phase_major : tmpdir_stagger_phase_minor]
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major : phase minor].
        # e.g, with default settings, a new plot will start only when your plot
        # reaches phase [2 : 1] on your temp drive. This setting takes precidence
        # over global_stagger_m
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1
        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 4
        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 8
        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 1
        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20
# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 3         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        #job_buffer: 6000     # Per job memory
        job_buffer: 6500     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        farmer_pk: verylong
        pool_pk:  verylongtoo
```
Does anyone have any idea how to solve it?
