### DISCUSSION TITLE
Validation of config

### DISCUSSION THREAD

**Discussion by cryptoisthefutur2000** [ericaltendorf/plotman#806] [Q&A] [answered]
HI all, I've been trying for a while now to get plotman optimized and I wanted to run my configuration by you all to see if you see any issues with it. Am I missing something obvious? Should I use a 3.5" drive as my dst? I recently switched to using archive instead of using my 3.5" drives as the dst folders. I'm having issues there but I started a different question to address that.

**Setup:**
CPU: Threadripper 3975wx (32 cores) 
256GB RAM 
6x NVMe drives at 1.9TB each at /mnt/tmp [1-6]
32 3.5" HDDs attached via USB vary in size from 1TB to 18TB at /mnt/farm/Chia Plots [0-31]

**My config:**
```
tmp:
                - /mnt/tmp 1
                - /mnt/tmp 2
                - /mnt/tmp 3
                - /mnt/tmp 4
                - /mnt/tmp 5

dst:
                 -/mnt/tmp 6

scheduling:

        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1
        
        tmpdir_max_jobs: 7

        global_max_jobs: 40

        global_stagger_m: 6

        polling_time_s: 20


plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 4         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 5000     # Per job memory

```
