### DISCUSSION TITLE
new configuration rsync

### DISCUSSION THREAD

**Discussion by thecodeassassin** [ericaltendorf/plotman#841] [Q&A] [answered]
Hi all,

This is my current config for rsyncd:

```

        archive:
                rsyncd_module: chia
                rsyncd_path: /mnt
                rsyncd_bwlimit: 1000000  # Bandwidth limit in KB/s
                rsyncd_host: 1.2.3.4
                rsyncd_user: user
```

the new config is something like:

```
archiving:
  target: rsyncd
  index: 0
  env:
    site_root: /mnt
    user: user
    host: 1.2.3.4
    rsync_port: 12000
    site: chia
````

I am a little bit fuzzy on the "site" argument, I guess site_root = rsyncd_path but I have no idea what the "site" argument should be. My destination drives are all /mnt/driveX, so /mnt/drive1, /mnt/drive2 etcetc.

**Comment by altendky** [comment, marked as answer]
Yep, the one bit you are missing is the bandwidth limit.  It seems you want to not have a limit.  See below for the defaults.  If you don't want a limit at all it is best to get rid of it entirely.

https://github.com/ericaltendorf/plotman/blob/3edef7ef97e0d4670322ae586823f4bbb1fc3c76/src/plotman/resources/target_definitions.yaml#L34

So, this looks like a reasonable upgraded form.

```yaml
archiving:
  target: rsyncd
  index: 0
  env:
    site_root: /mnt
    user: user
    host: 1.2.3.4
    rsync_port: 12000
    site: chia
    options: --preallocate --remove-source-files --skip-compress plot --whole-file
```

And yes, improved documentation and a configuration schema is on the long list of to-do's.
