### DISCUSSION TITLE
Error installing Plotman

### DISCUSSION THREAD

**Discussion by DendyDarzartar** [ericaltendorf/plotman#884] [Q&A]
I recently had to reinstall plotman as the 'plotman' command is no longer recognized in the chia environment.
Below are the errors I get when running the install command.

```
dendy@dendys-Farm:~/chia-blockchain$  > pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main
install: unrecognized option '--force-reinstall'
Try 'install --help' for more information.

dendy@dendys-Farm:~/chia-blockchain$  > pip install git+https://github.com/ericaltendorf/plotman@main 
install: missing destination file operand after 'git+https://github.com/ericaltendorf/plotman@main'
Try 'install --help' for more information.

dendy@dendys-Farm:~/chia-blockchain$ 
```

Should I be doing something differently to get it to run? It seems like it wants more to the command.

**Comment by altendky** [comment]
What does `pip --version` say?  I'm guessing it is fairly old.  It also seems like you didn't active the virtual environment.  That alone might be your issue.

**Reply by DendyDarzartar** [reply]
Hey, thank you for the response

Here is what I get when checking the version and trying the install again.

```
dendy@dendys-Farm:~$ pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

dendy@dendys-Farm:~$ cd chia-blockchain

dendy@dendys-Farm:~/chia-blockchain$ . ./activate

(venv) dendy@dendys-Farm:~/chia-blockchain$  > pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main
install: unrecognized option '--force-reinstall'
Try 'install --help' for more information.

(venv) dendy@dendys-Farm:~/chia-blockchain$  > pip install git+https://github.com/ericaltendorf/plotman@main 
install: missing destination file operand after 'git+https://github.com/ericaltendorf/plotman@main'
Try 'install --help' for more information.

(venv) dendy@dendys-Farm:~/chia-blockchain$ 
```

**Reply by altendky** [reply]
Don't have the `>` in the commands.  You aren't actually running `pip`, you are running `install` instead because of the `>`.

**Reply by DendyDarzartar** [reply]
Thank you, that seemed to do the trick but now I am running into a new problem when I try to run plotman commands

```python-traceback
(venv) dendy@dendys-Farm:~/chia-blockchain$ plotman status
Traceback (most recent call last):
  File "/home/dendy/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/dendy/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 171, in main
    with cfg.setup():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/dendy/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 433, in setup
    self.logging.setup()
  File "/home/dendy/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 273, in setup
    os.makedirs(self.plots, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/chia'
```

I'm not sure why it is giving me a permission issue. Any idea what I might have done wrong?

---

This is what I got when I ran through the install steps without the > 

```
dendy@dendys-Farm:~$ cd chia-blockchain
dendy@dendys-Farm:~/chia-blockchain$ . ./activate
(venv) dendy@dendys-Farm:~/chia-blockchain$ pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main
Collecting git+https://github.com/ericaltendorf/plotman@main
  Cloning https://github.com/ericaltendorf/plotman (to revision main) to /tmp/pip-req-build-ktrzbv_g
  Running command git clone -q https://github.com/ericaltendorf/plotman /tmp/pip-req-build-ktrzbv_g
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting psutil~=5.8
  Using cached psutil-5.8.0-cp38-cp38-manylinux2010_x86_64.whl (296 kB)
Collecting pyyaml~=5.4
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting pendulum~=2.1
  Using cached pendulum-2.1.2-cp38-cp38-manylinux1_x86_64.whl (155 kB)
Collecting attrs==21.2
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting packaging~=20.9
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting texttable~=1.6
  Using cached texttable-1.6.4-py2.py3-none-any.whl (10 kB)
Collecting marshmallow~=3.12
  Downloading marshmallow-3.13.0-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 1.9 MB/s 
Collecting desert==2020.11.18
  Using cached desert-2020.11.18-py3-none-any.whl (9.5 kB)
Collecting click~=7.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting typing-extensions~=3.10
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting appdirs~=1.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting typing-inspect
  Using cached typing_inspect-0.7.1-py3-none-any.whl (8.4 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil<3.0,>=2.6
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytzdata>=2020.1
  Using cached pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Building wheels for collected packages: plotman
  Building wheel for plotman (PEP 517) ... done
  Created wheel for plotman: filename=plotman-0.5.1-py3-none-any.whl size=77992 sha256=63059b8b1b84632ccc339936c967a5edd0990a9721b6891f3305de06d90739b5
  Stored in directory: /tmp/pip-ephem-wheel-cache-2o8jdku_/wheels/6e/4e/4d/284bb2756fdd9abdf6cbf8cc207251b72e1c81f806378c26fe
Successfully built plotman
Installing collected packages: typing-extensions, six, mypy-extensions, typing-inspect, pytzdata, python-dateutil, pyparsing, marshmallow, attrs, texttable, pyyaml, psutil, pendulum, packaging, desert, click, appdirs, plotman
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.0
    Uninstalling typing-extensions-3.10.0.0:
      Successfully uninstalled typing-extensions-3.10.0.0
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: attrs
    Found existing installation: attrs 21.2.0
    Uninstalling attrs-21.2.0:
      Successfully uninstalled attrs-21.2.0
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 5.4.1
    Uninstalling PyYAML-5.4.1:
      Successfully uninstalled PyYAML-5.4.1
  Attempting uninstall: click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
Successfully installed appdirs-1.4.4 attrs-21.2.0 click-7.1.2 desert-2020.11.18 marshmallow-3.13.0 mypy-extensions-0.4.3 packaging-20.9 pendulum-2.1.2 plotman-0.5.1 psutil-5.8.0 pyparsing-2.4.7 python-dateutil-2.8.2 pytzdata-2020.1 pyyaml-5.4.1 six-1.16.0 texttable-1.6.4 typing-extensions-3.10.0.0 typing-inspect-0.7.1
```

For what it may be worth, I edited the config.yaml after generating a new one as I had previously received an error mentioning the change in version. I was going to post it here but the preview looks kinda wonky and would probably be a little annoying to scroll through.

**Reply by altendky** [reply]
Do post it.  I edited your message to improve the formatting.  You can use triple backticks to surround it and label it as yaml, such as in the image.

![image](https://user-images.githubusercontent.com/543719/126730891-2367c068-ad63-43e5-a935-c02936ed6820.png)

That produces this output.

```yaml
some:
  config: here
```


Anyways, I'm guessing you did not edit the example config file's logging paths.  Specify where you want the logs to go, or comment out the configuration entirely for default locations.

https://github.com/ericaltendorf/plotman/blob/77f85e3b38abc45d8cb6af3bad650b458c3aef35/src/plotman/resources/plotman.yaml#L11

**Reply by DendyDarzartar** [reply]
Nice, that looks so much cleaner, thank you. 
The yaml config is below. 

```yaml

# Default/example plotman.yaml configuration file

# https://github.com/ericaltendorf/plotman/wiki/Configuration#versions
version: [2]

logging:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        plots: /home/chia/chia/logs
        # transfers:
        # application:

# Options for display and rendering
user_interface:
        # Call out to the `stty` program to determine terminal size, instead of
        # relying on what is reported by the curses library.   In some cases,
        # the curses library fails to update on SIGWINCH signals.  If the
        # `plotman interactive` curses interface does not properly adjust when
        # you resize the terminal window, you can try setting this to True. 
        use_stty_size: True

# Optional custom settings for the subcommands (status, interactive etc)
#commands:
       # interactive:
                # Set it to False if you don't want to auto start plotting when 'interactive' is ran.
                # You can override this value from the command line, type "plotman interactive -h" for details
                #autostart_plotting: True
                #autostart_archiving: True

# Where to plot and log.
directories:
        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - /mnt/plottingraid1

        # Optional: tmp2 directory.  If specified, will be passed to
        # chia plots create as -2.  Only one tmp2 directory is supported.
        # tmp2: /mnt/tmp/a

        # Optional: A list of one or more directories; the scheduler will
        # use all of them.  These again are presumed to be on independent
        # physical devices so writes (plot jobs) and reads (archivals) can
        # be scheduled to minimize IO contention.
        # 
        # If dst is commented out, the tmp directories will be used as the
        # buffer.
        dst:
                -  /media/dendy/Elements2/solo_plots

# Archival configuration.  Optional; if you do not wish to run the
# archiving operation, comment this section out.  Almost everyone
# should be using the archival feature.  It is meant to distribute
# plots among multiple disks filling them all.  This can be done both
# to local and to remote disks.
#
# As of v0.4, archiving commands are highly configurable.  The basic
# configuration consists of a script for checking available disk space
# and another for actually transferring plots.  Each can be specified
# as either a path to an existing script or inline script contents.
# It is expected that most people will use existing recipes and will
# adjust them by specifying environment variables that will set their
# system specific values.  These can be provided to the scripts via
# the `env` key.  plotman will additionally provide `source` and
# `destination` environment variables to the transfer script so it
# knows the specifically selected items to process.  plotman also needs
# to be able to generally detect if a transfer process is already
# running.  To be able to identify externally launched transfers, the
# process name and an argument prefix to match must be provided.  Note
# that variable substitution of environment variables including those
# specified in the env key can be used in both process name and process
# argument prefix elements but that they use the python substitution
# format.
#
# Complete example: https://github.com/ericaltendorf/plotman/wiki/Archiving
#archiving:
 # target: local_rsync
 # env:
  #  command: rsync
   # site_root: /farm/sites

# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before [tmpdir_stagger_phase_major : tmpdir_stagger_phase_minor]
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major : phase minor].
        # e.g, with default settings, a new plot will start only when your plot
        # reaches phase [2 : 1] on your temp drive. This setting takes precidence
        # over global_stagger_m
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 5

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 5

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 9

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 60

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20

        # Optional: Allows the overriding of some scheduling characteristics of the
        # tmp directories specified here.
        # This contains a map of tmp directory names to attributes. If a tmp directory 
        # and attribute is not listed here, the default attribute setting from the main 
        # configuration will be used
        #
        # Currently support override parameters:
        #     - tmpdir_stagger_phase_major (requires tmpdir_stagger_phase_minor)
        #     - tmpdir_stagger_phase_minor (requires tmpdir_stagger_phase_major)
        #     - tmpdir_stagger_phase_limit
        #     - tmpdir_max_jobs
     #   tmp_overrides:
                # In this example, /mnt/tmp/00 is larger and faster than the
                # other tmp dirs and it can hold more plots than the default,
                # allowing more simultaneous plots, so they are being started
                # earlier than the global setting above.
     #           "/mnt/tmp/00":
     #                   tmpdir_stagger_phase_major: 1
     #                   tmpdir_stagger_phase_minor: 5
     #                   tmpdir_max_jobs: 5
                # Here, /mnt/tmp/03 is smaller, so a different config might be
                # to space the phase stagger further apart and only allow 2 jobs
                # to run concurrently in it
     #           "/mnt/tmp/03":
     #                   tmpdir_stagger_phase_major: 3
     #                   tmpdir_stagger_phase_minor: 1
     #                   tmpdir_max_jobs: 2

# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        # Your public keys.  Be sure to use the pool contract address for
        # portable pool plots.  The pool public key is only for original
        # non-portable plots that can not be used with the official pooling
        # protocol.
        # farmer_pk: ...
        # pool_pk: ...
        # pool_contract_address: ...
        
        # If you enable Chia, plot in *parallel* with higher tmpdir_max_jobs and global_max_jobs
        type: chia
        chia:
                # The stock plotter: https://github.com/Chia-Network/chia-blockchain
                # executable: /path/to/chia
                k: 32                # k-size of plot, leave at 32 most of the time
                e: False             # Use -e plotting option
                n_threads: 3         # Threads per job
                n_buckets: 128       # Number of buckets to split data into
                job_buffer: 4408     # Per job memory

        # If you enable madMAx, plot in *sequence* with very low tmpdir_max_jobs and global_max_jobs
        madmax:
                # madMAx plotter: https://github.com/madMAx43v3r/chia-plotter
                # executable: /path/to/chia_plot
                n_threads: 4          # Default is 4, crank up if you have many cores
                n_buckets: 256        # Default is 256
```
