### DISCUSSION TITLE
Default archiving not actually archiving

### DISCUSSION THREAD

**Discussion by Proulx-S** [ericaltendorf/plotman#903] [Q&A] [answered]
I must have been doing some thing wrong.

Following the wiki on archiving, I uncommented the archiving section of my yaml configuration file and specified the archive mount point: in my case /mnt/plotting, where /mnt/plottingnft9_001, /mnt/plottingnft9_002, ... all my disks, are mounted.

That should be just it for local archive, no?

Yet, plots just stays in dst and archives don't increase in size.

rsync is working, tested on a dummy file, per the wiki.

Could not manually run the plotman rsync command. The wiki says to copy it from plotman interactive, but my plotman interactive somehow does not work.

Any ideas?

Thanks a lot for the help and
Happy plotting!
Sebastien

**Comment by altendky** [comment]
I have a few questions here.  First, you list drives such as `/mnt/plottingnft9_001`.  Is that correct or was it supposed to be `/mnt/plotting/nft9_001`?  Note the `/` after plotting.

Could you share your full configuration file here?  The "default" configuration doesn't have archive commented out.

https://github.com/ericaltendorf/plotman/blob/77f85e3b38abc45d8cb6af3bad650b458c3aef35/src/plotman/resources/plotman.yaml#L87-L91

What command are you using to run plotman?

And finally, could you share the output of `df -aBK`?

**Reply by Proulx-S** [reply]
Thanks for the quick reply. And sorry for the incomplete question, late night bug..

Yes, I meant /mnt/plotting/nft9_001.

Here is my config.yaml, stripped down a little for readability:
```yaml
# Default/example plotman.yaml configuration file

# https://github.com/ericaltendorf/plotman/wiki/Configuration#versions
version: [2]

logging:
        plots: /home/bass/Dropbox/chia/l_arnold

# Options for display and rendering
user_interface:
        use_stty_size: True

# Optional custom settings for the subcommands (status, interactive etc)
commands:
        interactive:
                autostart_plotting: True
                autostart_archiving: True

# Where to plot and log.
directories:
        tmp:
                - /mnt/SSD_PCIe0_2T/t
        #tmp2: 
        dst:
                - /mnt/SSD_SATA0_500G/f

# Archival configuration.
archiving:
  target: local_rsync
  env:
    command: rsync
    site_root: /mnt/plotting

# Plotting scheduling parameters
scheduling:
        tmpdir_stagger_phase_major: 4
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1
        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 2
        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 2
        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 1
        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20
# Plotting parameters.
plotting:
        farmer_pk: xxxxxxxxxxxx
        pool_contract_address: xxxxxxxxxxxx
        
        type: madmax
        madmax:
                # madMAx plotter: https://github.com/madMAx43v3r/chia-plotter
                # executable: /path/to/chia_plot
                n_threads: 15          # Default is 4, crank up if you have many cores
                n_buckets: 256        # Default is 256
```


And my disks mount setup:
```
bass@arnold:~/chia-blockchain$ df -aBK /mnt/SSD_PCIe0_2T/t /mnt/SSD_SATA0_500G/f /mnt/plotting/*
Filesystem       1K-blocks        Used   Available Use% Mounted on
/dev/md0       1921551568K  160415952K 1663456308K   9% /mnt/SSD_PCIe0_2T
/dev/sda1       479669928K  212622344K  242611924K  47% /mnt/SSD_SATA0_500G
/dev/sdm1      7814025212K 7687695464K  126329748K  99% /mnt/plotting/nft9_001
/dev/sdp1      7814025212K 7439359580K  374665632K  96% /mnt/plotting/nft9_010
/dev/sdo1      7814025212K 7758096892K   55928320K 100% /mnt/plotting/nft9_011
/dev/sdn1      7814025212K  425393272K 7388631940K   6% /mnt/plotting/nft9_012
/dev/sdi1      7814025212K  136158676K 7677866536K   2% /mnt/plotting/nft9_013
```

Finally, I also copy pasted the [Custom archiving setups](https://github.com/ericaltendorf/plotman/wiki/Archiving#custom-archiving-setups), to no avail, though it might be worth redoing, it was late at night.


Thanks a lot for the help and for the great work with plotman and
Have a good day!
Sebastien
