### DISCUSSION TITLE
Archiving without free space check

### DISCUSSION THREAD

**Discussion by mm0nst3r** [ericaltendorf/plotman#935] [Q&A]
Hello all! How can I set up archiving without checking free space?
I am rsyncing it to Truenas where Truenas's native Rsync module accepts it and then it is all being handled there properly. Truenas's Rsync just doesnt't support SSH and I don't want to create keys for my every plotter machine anyways
Now I am using following script outside of plotman:
`rsync --verbose --recursive --human-readable --include "*.plot" --exclude "*" --progress --remove-source-files "$file" rsync://username@192.168.1.71:873/rsync-buffer/pool-plots/`
where "rsync-buffer" is the module name on Truenas.
All I want from plotman is to rsync every new plot the similar way without checking free space.

Thnx

**Comment by altendky** [comment]
You can add your own custom target definition (such as https://github.com/ericaltendorf/plotman/blob/1b7dfba139ed03d3c32a2f04f6011e03bfb1f442/src/plotman/resources/target_definitions.yaml) into your existing `plotman.yaml` file and use it.  Something like below maybe, though I haven't actually run it.  I did leave the rsync options at the existing defaults instead of adding in verbose and recurse and so on.

Anyways, just a quick thing here so let me know what happens and we can adjust it...

```yaml
archiving:
  target: blind_rsyncd
  env:
    user: username
    host: 192.168.1.71
    site: rsync-buffer
    path_suffix: pool-plots
  target_definitions:
    blind_rsyncd:
      env:
        command: rsync
        options: --bwlimit=80000 --preallocate --remove-source-files --skip-compress plot --whole-file
        rsync_port: 873
        user: null
        host: null
        site: null
        path_suffix: ""
      disk_space_script: |
        #!/bin/bash
        set -evx
        # pretend that we are placing the plot into / and there is always 1PiB available
        echo /:1000000000000000
      transfer_script: |
        #!/bin/bash
        set -evx
        echo Launching transfer activity
        full_destination=$(realpath --canonicalize-missing "${destination}/${path_suffix}")
        # doesn't do as much as it used to, but reduces the diff to the original and strips the leading /
        relative_path=$(realpath --canonicalize-missing --relative-to="/" "${full_destination}")
        url_root="rsync://${user}@${host}:${rsync_port}/${site}"
        "${command}" ${options} "${source}" "${url_root}/${relative_path}/"
      transfer_process_name: "{command}"
      transfer_process_argument_prefix: "rsync://{user}@{host}:{rsync_port}/{site}"
```
