### DISCUSSION TITLE
Check disk space before starting plot

### DISCUSSION THREAD

**Discussion by Yamanipanuchi** [ericaltendorf/plotman#943] [Ideas]
It has been discussed about disk space considerations. But has it ever been suggested or looked into to see if PlotMon could check the destination for free disk space before starting its plot?

Seems with plots going so fast now days it would be a nice feature?

**Comment by altendky** [comment]
https://github.com/ericaltendorf/plotman/wiki/Archiving

`dst` isn't meant to be the final resting place for plots, despite it's name.  Archiving is there to handle that.  I personally mostly don't even use `dst` anymore and just archive straight from my `tmp` disks.

**Reply by Yamanipanuchi** [reply]
That is basically what I want to do, Is archive from the tmp disks. How do I setup the config to do this?

**Comment by Yamanipanuchi** [comment]
I have this setting in place...

```yaml
        tmp:
                - /plotter01
                - /plotter02
```

and I have the following also

```yaml
        dst:
                - /plots01
                - /plots02
                - /plots03
```

I have this set for archive (The drive are on the same machine)

```yaml
archiving:
        target: rsyncd
        env:
                site_root: /mnt/dest
                #user: root
                #host: aragorn
                #rsync_port: 12000
                #site: disks
```
With these setting it still show the destination as `/plots01`. I dont seem to be able to see a setting to leave the plot on the tmp drive to let archiving take care of it.

Also it is same to assume that even with archive enabled the script still does not take in consideration weather the drive is full or not right?

**Reply by altendky** [reply]
I comment out the `dst:` section entirely.  With your `site_root: /mnt/dest` setting you need to be sure that your target disks are mounted such as `/mnt/dest/a_disk` and `/mnt/dest/another_disk`.

The plotter side will keep plotting until it has reason to stop based on it's own scheduling.  Full archive destinations will not directly block launching new plots.  The archiving itself will pay attention to which disks have space and will push the plots until all drives are full.  I even end up adding and removing disks without reconfiguring nor restarting plotman and it just keeps on filling them via archiving.

**Reply by Yamanipanuchi** [reply]
Looks as if that was the piece I was missing, Commented dst out and it looks like its doing what I expected.

Thanks for the help!

**Reply by Yamanipanuchi** [reply]
Curios, if the archive part of the script cannot find a drive with space what does it do? I know eventually ill find out, But I have sometime till I get there.

**Reply by Yamanipanuchi** [reply]
Ya, So the script just left the plot on the plotting disk and never moved it. So that didn't work.

**Reply by altendky** [reply]
What would you want it to do when there's nowhere to archive to?  But yes, if it can't find a disk with sufficient space it does nothing instead of start a copy that will almost certainly fail.

**Reply by altendky** [reply]
Or perhaps I misunderstood and you were just saying that apparently the configuration wasn't quite right yet.

**Reply by Yamanipanuchi** [reply]
Ya I don't think it was quite right. I like the idea of being able to swap the drives out between plot copies so I would like to see it work.

I had my config as follows..


```yaml
        tmp:
                - /plotter01
                - /plotter02

        # tmp2: /plotting2
#        dst:
#                - /plots01
#               - /plots02
#                - /plots03

archiving:
        target: rsyncd
        env:
                site_root: /mnt/dest
                #user: root
                #host: 
                #rsync_port: 12000
                #site: disks
```


I had a plot going on both Plotter1 and Plotter2, Once those plots complete the plot files just hung out in the temp folder. I guess I assumed it would move the files to one of the three drives under /mnt/dst. Each of these drives have plenty of space.
