### ISSUE TITLE
[BUG]The job task grows indefinitely until the cache hard disk runs out of space

### ISSUE THREAD

**Issue by peterwillcn** [ericaltendorf/plotman#149]
The job task grows indefinitely until the cache hard disk runs out of space

**Comment by altendky** [comment]
I'm sorry, I'm not clear what is being reported here.  What files are taking up space?  Which drive are you referring to?  The usual terminology here is something like tmp, tmp2, dst, and then just wherever everything else like chia and plotman and the OS etc go.

**Comment by BasilHorowt** [comment]
@peterwillcn any chance you are on OSX?  There was a fixed issue related to that platform but I don't believe it's been merged into main yet https://github.com/ericaltendorf/plotman/pull/142

**Comment by zrjaa1** [comment]
+1. Running plotman in WSL2 with 1 tmp drive and 1 dst drive without archiving:

```
directories:
        log: /home/jay/chia-blockchain/plotman-logs
        tmp:
                - /mnt/p
        tmp_overrides:
                "/mnt/p":
                        tmpdir_max_jobs: 8

        # tmp2: /mnt/tmp/a

        dst:
                - /mnt/d
                - 
        # archive:
                # rsyncd_module: plots
                # rsyncd_path: /plots
                # rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
                # rsyncd_host: myfarmer
                # rsyncd_user: chia
```

 Here is my configuration for scheduling:

```
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 2

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 8

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 10

        # Don't run any jobs (across all temp dirs) more often than this.
        global_stagger_m: 10

        # How often the daemon wakes to consider starting a new plot job
        polling_time_s: 20
```

My understanding is that maximum of 8 jobs will be created with this configuration, and `plotman status` should be able to display the status of all the 8 jobs. However, there are 10 plotting logs created and the `plotman status` only shows 2 jobs：

```
(venv) root@JAY-DESKTOP:/home/jay/chia-blockchain/plotman-logs# ls
2021-04-23-16:44:25.log  2021-04-23-17:23:34.log  2021-04-23-18:22:51.log  2021-04-23-20:01:25.log
2021-04-23-16:54:26.log  2021-04-23-17:38:59.log  2021-04-23-18:54:41.log
2021-04-23-17:09:51.log  2021-04-23-17:53:23.log  2021-04-23-19:28:13.log
(venv) root@JAY-DESKTOP:/home/jay/chia-blockchain/plotman-logs# plotman status
 plot id    k      tmp      dst   wall   phase    tmp    pid   stat    mem   user    sys   io
3bef6f46   32   /mnt/p   /mnt/d   0:20     1:2    68G   8034    SLP   5.4G   0:19   0:03   0s
b8a0387a   32   /mnt/p   /mnt/d   0:54     1:3   111G   7943    SLP   5.4G   0:47   0:04   0s
```

Did I miss anything or mis-understand the configuration? Please help, thanks!
