### ISSUE TITLE
Where Did My Plots Go?

### ISSUE THREAD

**Issue by michael-pptf** [ericaltendorf/plotman#156]
Hello, 

Been testing plotman for the past two days with little success. I have a NAS dir mounted to my Ubuntu Server and set as dst. I am not running archiver so I commented that section out in the config.yaml. However, when the jobs are done, I do not see any .plot files in my dst folder. So where did those completed plots go?

**Comment by altendky** [comment]
I'm sorry you are having trouble.  I don't know what happened.  Could you share:

- your full config file
- a copy of the plotman screen showing it plotting
- the commands you are running and output that show the lack of plot files where you expect
- the output of `df -h`

**Comment by michael-pptf** [comment]
Hi, thanks for the timely reply.

Upon further investigation myself, I was able to see why it didn't appear where it should - Job was not yet complete even if they are in "4:0" status. This job took over 50k secs to complete. I guess something is wrong with my system since mine takes approx. 19k secs to complete a job.

However, there was this one thing that bothered me. I was looking at two parallel jobs showing the status of "4:0", but they did not start to move to dst folder. Is there a pause timer before the move to dst?

**Comment by altendky** [comment]
As far as I know that's all in the chia plotter code.  I am not aware of a delay.  I would guess it is having issues writing to the dst location.  I've had that happen when my dst is full.  I think I also had it happen when dst had the wrong permissions, perhaps.  Maybe the plot log has a message?

Depending on the system and parallel plots etc, 12+ hours is not crazy.

**Comment by michael-pptf** [comment]
Most likely it is not the permissions since the completed plot showed up before I typed up the response above, so chia plotter, plotman, and my user acct has the permission to write to dst folder.

Dst folder has more than 7TB avail, so that's not the problem either.

Is there a plotman log that I can do a further investigation?

**Comment by michael-pptf** [comment]
This is the current screenshot of my jobs list. There were eight, one was completed as I typed up the question. As you can see, there are two "4:0" jobs, however only one is being transferred to dst as we speak.

![image](https://user-images.githubusercontent.com/59861321/115893460-0d52ea80-a40d-11eb-8009-12f3f12c0634.png)

**Comment by altendky** [comment]
No, there is presently no plotman log.  That is a thing I want to change but it likely wouldn't relate much to this.  Once the chia plot process has started, plotman does nothing but keep an eye on it.  The chia plotter is entirely in control.  Chia seems to copy to a `.plot.2.tmp` file on the tmp drive which is then renamed to just `.plot` I think as it is copied to dst.  So, perhaps you are observing this?  Though this may vary depending on tmp/tmp2/dst locations.

```
-rw-rw-r-- 1 chia chia 102G Apr 23 15:36 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.2.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_114.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_115.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_116.tmp
-rw-rw-r-- 1 chia chia 289M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_117.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_118.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_119.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_120.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_121.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_122.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_123.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_124.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_125.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_126.tmp
-rw-rw-r-- 1 chia chia 288M Apr 23 15:08 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.p3s.t7.sort_bucket_127.tmp
-rw-rw-r-- 1 chia chia    0 Apr 22 22:49 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.sort.tmp
-rw-rw-r-- 1 chia chia    0 Apr 23 08:54 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.table1.tmp
-rw-rw-r-- 1 chia chia    0 Apr 23 08:24 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.table2.tmp
-rw-rw-r-- 1 chia chia    0 Apr 23 08:03 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.table3.tmp
-rw-rw-r-- 1 chia chia    0 Apr 23 07:41 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.table4.tmp
-rw-rw-r-- 1 chia chia    0 Apr 23 07:19 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.table5.tmp
-rw-rw-r-- 1 chia chia    0 Apr 23 06:57 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.table6.tmp
-rw-rw-r-- 1 chia chia  40G Apr 23 14:04 plot-k32-2021-04-22-22-49-5e3d7d1a5f118d3e85cb15035239417938e9e62d6fb84318561dd5cc230e0e58.plot.table7.tmp
```

I'm sorry that I don't know the nuances here about what all happens in 4:0 and why there may be a delay between the start of 4:0 and some files showing up in the dst (is that where you are looking?).  Perhaps you can get better support on those details in the chia support channel on keybase.

**Comment by michael-pptf** [comment]
Thank you nonetheless for the timely and professional response.

Would you mind to elaborate a little on the settings for:

- tmpdir_stagger_phase_major: 2
- tmpdir_stagger_phase_minor: 1
-  tmpdir_stagger_phase_limit: 1

Per my little understanding, the phase limit determines max jobs to be ran at once. If I wanted 8 jobs in parallel, this should be set to 8?

From there, how do I interpret the major and minor limits? If I just want them to be separated for 15 minutes in between, is this a right setup? My config is as follows:

```

     
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before tmpdir_stagger_phase_major tmpdir_stagger_phase_minor
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major, phase minor]
        tmpdir_stagger_phase_major: 4
        tmpdir_stagger_phase_minor: 4
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 8

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 8

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 8

        # Don't run any jobs (across all temp dirs) more often than this.
        global_stagger_m: 15

        # How often the daemon wakes to consider starting a new plot job
        polling_time_s: 20



```
