### ISSUE TITLE
Create plots over config limit

### ISSUE THREAD

**Issue by Sojtin** [ericaltendorf/plotman#265]
Plotman (0.2) on ubuntu (20.04) creating plots over my config limit, basically it creates new plot on each iteration.

```
plotman plot                                                                                                                                       
...starting plot loop
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-07:56:25.log')
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-07:58:05.log')
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-07:59:46.log')
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-08:01:26.log')
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-08:03:06.log')
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-08:04:46.log')
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-08:06:26.log')
...sleeping 100 s: (True, 'Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 5000 -t /ssd_raid/plotman_01 -d /storage/chiaPlots -f xx -p xx ; logging to /home/chiaLogs/2021-05-07-08:08:06.log')

```

config:
```yaml
 scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 6

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 6

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 70

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 100

plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 4         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 5000     # Per job memory
```

`plotman status` shows empty array but processes actually starting.
