### ISSUE TITLE
archive sees no drives available 

### ISSUE THREAD

**Issue by chadmccune** [ericaltendorf/plotman#349]
I'm trying to use the archival feature to copy to my main machine (which happens to be windows until some additional hardware arrives).

I'm running rsync inside ubuntu on wsl2.  The host drives are all auto mounted under /mnt/[windows drive letter]

I obviously don't want to sync to every drive on my windows machine, so I tried creating a diretory  /chiaplots and adding symlinks to the mounted drives inside it

```bash
cd /chiaplots
ln -s /mnt/p/PlotsFinal ./drive_p
ln -s /mnt/q/PlotsFinal ./drive_q
```

Running rsync manually from the plotting machine is able to successfully copy files, but  plotman says "No free archive dirs found."

rsyncd.conf

```
port = 12000
use chroot = false
read only = false

[chia]
  path = /chiaplots
  read only = no
  list = yes
  hosts allow = [plotter ip]
```

plotman.yaml

```
        archive:
                rsyncd_module: chia
                rsyncd_path: /chiaplots
                rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
                rsyncd_host: [windows ip]
                rsyncd_user: [username]
```

Do I have something misconfigured?
