### ISSUE TITLE
Plotman REMOVED plotted file when full DST drive caused plot copy to break during transfer

### ISSUE THREAD

**Issue by zette** [ericaltendorf/plotman#395]
Plotman v0.2
During plotting the DST drive became full to the extent that next plot would not fit. When another plot was finished it started copying to DST, but hitting the drive full it stopped and plotman removed the source file as if it has been safely stored in DST.
**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Fill up DST so, next plot would not fit.
3. Run Plotman with DST set
4. During copying of the finished plot to DST it would stop and remove source file leaving partial file in DST.

**Expected behavior**
Plotman waits with removal of source file until it has been fully stored on DST (at least add the file size verification)

**System setup:**
 - Ubuntu 20.10
 - Method of archiving none

**Config**
<details> <summary>full configuration</summary>

```yaml
user_interface:
        use_stty_size: True
directories:
        log: /home/chia/logs
        tmp:
                - /mnt/chia/0
                - /mnt/chia/1
        tmp_overrides:
                "/mnt/chia/0":
                        tmpdir_max_jobs: 3
                "/mnt/chia/1":
                        tmpdir_max_jobs: 2
        dst:
                 - /mnt/chia/buffer

scheduling:
        tmpdir_stagger_phase_major: 1
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1
        tmpdir_max_jobs: 8
        global_max_jobs: 12
        global_stagger_m: 60
        polling_time_s: 60
plotting:
        k: 32
```

</details>

**Additional context & screenshots**
```plotman log
/home/zt/chia/logs/2021-05-12-19:38:03.log:ID: 4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a
/home/zt/chia/logs/2021-05-12-19:38:03.log:Starting phase 3/4: Compression from tmp files into "/mnt/chia/array/plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot.2.tmp" ... Thu May 13 02:33:28 2021
/home/zt/chia/logs/2021-05-12-19:38:03.log:Starting phase 4/4: Write Checkpoint tables into "/mnt/chia/array/plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot.2.tmp" ... Thu May 13 06:29:39 2021
/home/zt/chia/logs/2021-05-12-19:38:03.log:Copied final file from "/mnt/chia/array/plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot.2.tmp" to "/mnt/chia/buffer/plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot.2.tmp"
/home/zt/chia/logs/2021-05-12-19:38:03.log:Removed temp2 file "/mnt/chia/array/plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot.2.tmp"? 1
/home/zt/chia/logs/2021-05-12-19:38:03.log:Renamed final file from "/mnt/chia/buffer/plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot.2.tmp" to "/mnt/chia/buffer/plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot"
```
```ls -lh
-rw-r--r-- 1 zt zt    93G May 13 06:56 plot-k32-2021-05-12-19-38-4594123bfbbcb97a4a729f883a9096384570828b3c8d5aa9cef16260fd9fbe0a.plot
```
