### ISSUE TITLE
Jobs stall and die silently

### ISSUE THREAD

**Issue by ASAPHAANING** [ericaltendorf/plotman#556]
**Describe the bug**
Running with no settings changed off the default template on an Intel NUC (8G mem, 500Gb NVMe) and an older desktop respectively I reach the following state roughly 20 hours after starting (the same pattern is observed on both):

```
(venv) haaning@debian2:~/chia-blockchain$ plotman status     
plot id    k            tmp            dst    wall   phase    tmp     pid   stat    mem   user    sys     io
25430078   32   /home/haanin   /mnt/big-dis    5:12     1:3   130G   26578    SLP   4.0G   1:56   0:04     2s
                   g/plottmp   k/Chia/final                                                                  
                                          /                                                                  
5681af4f   32   /mnt/expansi   /mnt/big-dis    7:34     1:3   147G   26503    SLP   4.0G   2:47   0:10    52s
                on-big/plott   k/Chia/final                                                                  
                        mp2/              /                                                                  
d26c9a5d   32   /home/haanin   /mnt/big-dis   10:06     2:4   237G   26279    SLP   1.5G   7:55   0:19   0:11
                   g/plottmp   k/Chia/final                                                                  
                                          /                                                                  
95e39066   32   /mnt/expansi   /mnt/big-dis   19:23     2:5   233G   25804    SLP   1.5G   9:54   0:28   4:04
                on-big/plott   k/Chia/final                                                                  
```

Coming back after ~2 hours I observe that the long-running plot simply seemingly died. This was also the case on the older desktop:

```
(venv) haaning@debian2:~/chia-blockchain$ plotman status
 
plot id    k            tmp            dst    wall   phase    tmp     pid   stat    mem   user    sys     io
25430078   32   /home/haanin   /mnt/big-dis    7:03     1:3   130G   26578    SLP   4.0G   1:56   0:04     2s
                   g/plottmp   k/Chia/final                                                                  
                                          /                                                                  
5681af4f   32   /mnt/expansi   /mnt/big-dis    9:25     1:3   163G   26503    SLP   4.0G   3:40   0:14   0:01
                on-big/plott   k/Chia/final                                                                  
                        mp2/              /                                                                  
d26c9a5d   32   /home/haanin   /mnt/big-dis   11:57     2:4   237G   26279    SLP   1.5G   7:55   0:19   0:11
                   g/plottmp   k/Chia/final                                                                  
                                          /                                                                  
(venv) haaning@debian2:~/chia-blockchain$ ls /mnt/big-disk/Chia/final/
(venv) haaning@debian2:~/chia-blockchain$ 
```

Running details on the missing job yields nothing:

```
(venv) haaning@debian2:~/chia-blockchain$ plotman details 95e39066
Namespace(cmd='details', idprefix=['95e39066'])
Error: 95e39066 matched no jobs.
```

Before I could run 3 plot jobs concurrently without problems. Grepping the plotman yields the some of these:

```
/home/haaning/plotman/logs/2021-05-18T08_50_57.918405+02_00.log:Only wrote 495670 of 1048554 bytes at offset 588238794 to "/home/haaning/plottmp/plot-k32-2021-05-18-08-50-<hash>.plot.p1.t3.sort_bucket_097.tmp"with length 588734464. Error 1. Retrying in five minutes.

/home/haaning/plotman/logs/2021-05-18T03_03_50.115576+02_00.log:Caught plotting error: std::bad_alloc
/home/haaning/plotman/logs/2021-05-18T03_03_50.115576+02_00.log:RuntimeError: std::exception
```

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Set up config with 'default settings'
2. Run other programs 'None'
3. Run Plotman with 'plotman plot'

**Expected behavior**

**System setup:**
 - OS: [e.g. Ubuntu, iOS, ...]
 - **Debian**
 - Method of archiving 
 - **Manual** (None so far)

**Config**
<details> <summary>full configuration</summary>

```yaml
# Default/example plotman.yaml configuration file

# Options for display and rendering
user_interface:
        # Call out to the `stty` program to determine terminal size, instead of
        # relying on what is reported by the curses library.   In some cases,
        # the curses library fails to update on SIGWINCH signals.  If the
        # `plotman interactive` curses interface does not properly adjust when
        # you resize the terminal window, you can try setting this to True. 
        use_stty_size: True

# Where to plot and log.
directories:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        log: /home/haaning/plotman/logs

        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - /home/haaning/plottmp
                - /mnt/expansion-big/plottmp2/

        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        #tmp_overrides:
                # In this example, /mnt/tmp/00 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                #       "/mnt/tmp/00":
                #       tmpdir_max_jobs: 5

        # Optional: tmp2 directory.  If specified, will be passed to
        # chia plots create as -2.  Only one tmp2 directory is supported.
        # tmp2: /mnt/tmp/a

        # One or more directories; the scheduler will use all of them.
        # These again are presumed to be on independent physical devices,
        # so writes (plot jobs) and reads (archivals) can be scheduled
        # to minimize IO contention.
        dst:
                - /mnt/big-disk/Chia/final/
               

        # Archival configuration.  Optional; if you do not wish to run the
        # archiving operation, comment this section out.
        #
        # Currently archival depends on an rsync daemon running on the remote
        # host.
        # The archival also uses ssh to connect to the remote host and check
        # for available directories. Set up ssh keys on the remote host to
        # allow public key login from rsyncd_user.
        # Complete example: https://github.com/ericaltendorf/plotman/wiki/Archiving
        #archive:
        #        rsyncd_module: plots # Define this in remote rsyncd.conf.
        #        rsyncd_path: /plots # This is used via ssh. Should match path
        #                           # defined in the module referenced above.
        #       rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
        #       rsyncd_host: myfarmer
        #       rsyncd_user: chia
                # Optional index.  If omitted or set to 0, plotman will archive
                # to the first archive dir with free space.  If specified,
                # plotman will skip forward up to 'index' drives (if they exist).
                # This can be useful to reduce io contention on a drive on the
                # archive host if you have multiple plotters (simultaneous io
                # can still happen at the time a drive fills up.)  E.g., if you
                # have four plotters, you could set this to 0, 1, 2, and 3, on
                # the 4 machines, or 0, 1, 0, 1.
                #   index: 0


# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before [tmpdir_stagger_phase_major : tmpdir_stagger_phase_minor]
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major : phase minor].
        # e.g, with default settings, a new plot will start only when your plot
        # reaches phase [2 : 1] on your temp drive. This setting takes precidence
        # over global_stagger_m
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 4

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 7 

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 30

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20


# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 2         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3389     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
```

</details>

**Additional context & screenshots**
