### ISSUE TITLE
only one tmp used at least when using madmax

### ISSUE THREAD

**Issue by altendky** [ericaltendorf/plotman#807]
I have a problem  

5950x + 3* 2T nvme

Looking at my setup, the results are not what I expected
```yaml
version: [2]

directories:
        tmp:
                - /ssd1/Plotter
                - /ssd2/Plotter
                - /ssd3/Plotter

        tmp_overrides:
                "/ssd1/Plotter":
                        tmpdir_max_jobs: 2

                "/ssd2/Plotter":
                        tmpdir_max_jobs: 2

                "/ssd3/Plotter":
                        tmpdir_max_jobs: 2

        dst:
                - /d/Plots
                - /e/Plots
                - /f/Plots
                - /g/Plots
                - /h/Plots

scheduling:

        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1
        tmpdir_max_jobs: 2
        global_max_jobs: 6
        global_stagger_m: 5
        polling_time_s: 20

        type: madmax
  
        madmax:
                n_threads: 8         
                n_buckets: 256       
```
![1624514385031](https://user-images.githubusercontent.com/19262346/123210466-9f05d380-d4f4-11eb-9c41-8a9696500390.jpg)

_Originally posted by @wasdokij in https://github.com/ericaltendorf/plotman/pull/797#issuecomment-867360811_

**Comment by altendky** [comment]
_Originally posted by @Pencerval in https://github.com/ericaltendorf/plotman/pull/797#issuecomment-867510101_

Same here. I'm triggering the same issue. 2 different temp dirs only 1 used. 
Also, looks like tmpdir_stagger_phase_major is not being used. 



```yaml
directories:
        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - /plot_temp/1
                - /plot_temp/2

        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        #tmp_overrides:
                # In this example, /mnt/tmp/00 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                #"/mnt/tmp/00":
                #        tmpdir_max_jobs: 5
`

`
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before [tmpdir_stagger_phase_major : tmpdir_stagger_phase_minor]
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major : phase minor].
        # e.g, with default settings, a new plot will start only when your plot
        # reaches phase [2 : 1] on your temp drive. This setting takes precidence
        # over global_stagger_m
        tmpdir_stagger_phase_major: 4
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Dont run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 2

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 4

        # Dont run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 1

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20
```

```
plot id   plotter    k           tmp           dst   wall   phase    tmp       pid   stat     mem   user    sys   io
9e735167    madmax   32   /plot_temp/   /mnt/hubusb   0:49     4:0   109G   2546991    SLP   4.2Gi   8:07   0:39   0s
                                   1/   1/disk1/plo
                                                ts/
6ece507b    madmax   32   /plot_temp/   /farm/1/dis   8:43     4:0   109G   2259637    SLP   5.4Gi   8:44   0:50   0s
                                   1/     k2/plots/

Total jobs: 2
Jobs in /plot_temp/1/: 2

Updated at: Thu Jun 24 10:03:22 2021
```
