### ISSUE TITLE
256 Bucket issue

### ISSUE THREAD

**Issue by Spaikys** [ericaltendorf/plotman#843]
Hello, i was trying to set my buckets to 256 instead of 128, and unfortunately plotman goes in to loop mode, trying to create job every 20 seconds but fails. as soon as i set it back to 128 in config file, everything is okay and plotman creates a new job.
What could be issue regarding this?

**Comment by altendky** [comment]
Could you share the corresponding plot log?  Hopefully there's a useful message there.

**Comment by Spaikys** [comment]
> Could you share the corresponding plot log? Hopefully there's a useful message there.

Thisi is what i se in log file 
[2021-07-09T20_12_47.343856+01_00.plot.log](https://github.com/ericaltendorf/plotman/files/6793704/2021-07-09T20_12_47.343856%2B01_00.plot.log)

**Comment by Spaikys** [comment]
This is my Config file
```

# https://github.com/ericaltendorf/plotman/wiki/Configuration#versions
version: [1]

logging:
        plots: /home/cool/.chia/mainnet/plotman/plots
        transfers: /home/cool/.chia/mainnet/plotman/transfers
        application: /home/cool/.chia/mainnet/plotman/plotman.log

user_interface:
        use_stty_size: True

        interactive:
                autostart_plotting: True
                autostart_archiving: True

directories:
        tmp:
                - /PNY 2TB
                - /home/cool/ChiaTemp

        tmp_overrides:
                "/PNY 2TB":
                        tmpdir_max_jobs: 5
                "/home/cool/ChiaTemp":
                        tmpdir_max_jobs: 3
        dst:
                - /SEAGATE 2TB
                - 
archiving:
  target: rsyncd
  env:
    site_root: /mnt/farm
    user: data1
    host: 192.168.0.70
    rsync_port: 12000
    site: chia

scheduling:
        tmpdir_stagger_phase_major: 1
        tmpdir_stagger_phase_minor: 5
        tmpdir_stagger_phase_limit: 2
        tmpdir_max_jobs: 5
        global_max_jobs: 8
        global_stagger_m: 45
        polling_time_s: 20

plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 4         # Threads per job
        n_buckets: 256       # Number of buckets to split data into
        job_buffer: 3600     # Per job memory
       
```
