### ISSUE TITLE
archiving issue

### ISSUE THREAD

**Issue by chriscrutt** [ericaltendorf/plotman#955]
**Describe the bug**
Looking at the [**Archiving**](https://github.com/ericaltendorf/plotman/wiki/Archiving#update-your-plotmanyaml) tutorial, it says to add `archive` with various bits of info in `plotman.yaml`. I was confused because `archiving` already exists. And when I add it, I receive: 
 > plotman.configuration.ConfigurationException: Config file at: '/home/username/.config/plotman/plotman.yaml' is malformed

**To Reproduce**

Set up `plotman.yaml` as
```yaml
version: [2]
user_interface:
        use_stty_size: True

commands:
        interactive:
                autostart_plotting: True
                autostart_archiving: True

directories:
        tmp:
                - /mnt/tmp/tmpdir
                - /mnt/tmp/tmpdir2
archiving:
        target: local_rsync
        env:
                command: rsync
                site_root: /mnt/archives

archive: # here's the added thing that causes the issue
        rsyncd_module: chia
        rsyncd_path: /mnt/archives
        rsyncd_bwlimit: 100000
        rsyncd_host: localhost
        rsyncd_user: username

scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1

        tmpdir_max_jobs: 5

        global_max_jobs: 9

        global_stagger_m: 30

        polling_time_s: 20

plotting:

        farmer_pk: asdf
        pool_contract_address: asdf
        
        type: chia
        chia:
                k: 32
                e: False
                n_threads: 3
                n_buckets: 128
                job_buffer: 6500

        madmax:
                n_threads: 4
                n_buckets: 256
                n_buckets3: 256
                n_rmulti2: 1
                
        bladebit:
                threads: 2
                no_numa: false
```
run `plotman interactive`

Is it just depreciated? Do I even need to include it? I don't want to plot for a few hours and then have it not archiving.

**System setup:**
 - OS: Ubuntu 20.04.4 LTS
 - Python Version 3.8.10

edit: readability

**Comment by zorner** [comment]
I am guessing an out of date document/wiki. Look at: [Archiving](https://github.com/ericaltendorf/plotman/wiki/Archiving)

```
archiving:
  target: rsyncd
  env:
    site_root: /mnt/farm
    user: username
    host: plot.storage.ip
    rsync_port: 12000
    site: sites
```

It needs a target and then the other variables get set in the env section.
